import type { Replay, Run } from '@agent-studio/contracts';

import { seededOperationalContexts } from './recommendations.js';
import { seededIds, seededStudioState, seededWorkflow } from './workflows.js';

export const seededRuns = [
  {
    runId: seededIds.baselineRunId,
    workflowId: seededIds.workflowId,
    status: 'succeeded',
    startedAt: '2026-04-17T13:00:00.000Z',
    finishedAt: '2026-04-17T13:09:20.000Z',
    estimatedCredits: 30,
    actualCredits: 32,
    durationMs: 560000,
    experimentId: seededIds.baselineExperimentId,
    experimentLabel: 'Baseline control',
    branchName: 'control',
    scenarioId: seededIds.scenarioId,
    scenarioLabel: 'Weekly operations brief',
    previewPresetId: seededIds.recommendedPresetId,
    previewPresetLabel: 'Recommended',
    matchedSavedExperiment: true,
  },
  {
    runId: seededIds.degradedRunId,
    workflowId: seededIds.workflowId,
    status: 'failed',
    startedAt: '2026-04-18T13:00:00.000Z',
    finishedAt: '2026-04-18T13:10:40.000Z',
    estimatedCredits: 33,
    actualCredits: 35,
    durationMs: 640000,
    experimentId: seededIds.degradedExperimentId,
    experimentLabel: 'Lean review failure',
    branchName: 'lean-review',
    parentExperimentId: seededIds.baselineExperimentId,
    scenarioId: seededIds.scenarioId,
    scenarioLabel: 'Weekly operations brief',
    previewPresetId: seededIds.leanPresetId,
    previewPresetLabel: 'Lean ops',
    matchedSavedExperiment: false,
  },
  {
    runId: seededIds.improvedRunId,
    workflowId: seededIds.workflowId,
    status: 'succeeded',
    startedAt: '2026-04-19T13:00:00.000Z',
    finishedAt: '2026-04-19T13:07:54.000Z',
    estimatedCredits: 21,
    actualCredits: 20,
    durationMs: 474000,
    experimentId: seededIds.improvedExperimentId,
    experimentLabel: 'Guardrailed candidate',
    branchName: 'optimize-brief',
    parentExperimentId: seededIds.baselineExperimentId,
    matchedSavedExperiment: true,
    scenarioId: seededIds.scenarioId,
    scenarioLabel: 'Weekly operations brief',
    previewPresetId: seededIds.optimizedPresetId,
    previewPresetLabel: 'Optimized brief',
  },
] satisfies Run[];

const baselineReplay: Replay = {
  workflow: seededWorkflow,
  run: seededRuns[0],
  stepExecutions: [
    {
      stepId: 'capture-intake',
      kind: 'capture',
      title: 'Capture intake and context',
      assignedRole: 'coordinator',
      status: 'succeeded',
      startedAt: '2026-04-17T13:00:00.000Z',
      finishedAt: '2026-04-17T13:01:18.000Z',
      durationMs: 78000,
      modelTier: 'micro',
      modelSource: 'control-room',
      directiveMode: 'cheaper',
      directivePhases: ['capture', 'search'],
      toolCalls: 1,
      actualCredits: 4,
      tokenUsage: {
        inputTokens: 2100,
        outputTokens: 640,
        totalTokens: 2740,
      },
      summary: 'Normalized the request and grouped it with the active queue.',
    },
    {
      stepId: 'collect-evidence',
      kind: 'search',
      title: 'Collect supporting evidence',
      assignedRole: 'researcher',
      status: 'succeeded',
      startedAt: '2026-04-17T13:01:20.000Z',
      finishedAt: '2026-04-17T13:03:30.000Z',
      durationMs: 130000,
      modelTier: 'micro',
      modelSource: 'search-runtime',
      directiveMode: 'cheaper',
      directivePhases: ['search'],
      toolCalls: 4,
      actualCredits: 9,
      tokenUsage: {
        inputTokens: 3600,
        outputTokens: 960,
        totalTokens: 4560,
      },
      summary: 'Collected seven relevant sources and marked two low-confidence items.',
    },
    {
      stepId: 'normalize-evidence',
      kind: 'capture',
      title: 'Normalize notes into a fact table',
      assignedRole: 'annotator',
      status: 'succeeded',
      startedAt: '2026-04-17T13:03:32.000Z',
      finishedAt: '2026-04-17T13:05:04.000Z',
      durationMs: 92000,
      modelTier: 'default',
      modelSource: 'notes-engine',
      toolCalls: 2,
      actualCredits: 5,
      tokenUsage: {
        inputTokens: 2400,
        outputTokens: 740,
        totalTokens: 3140,
      },
      summary: 'Turned the source pile into a compact cited fact table.',
    },
    {
      stepId: 'synthesize-brief',
      kind: 'analyze',
      title: 'Synthesize the recommendation',
      assignedRole: 'analyst',
      status: 'succeeded',
      startedAt: '2026-04-17T13:05:06.000Z',
      finishedAt: '2026-04-17T13:07:36.000Z',
      durationMs: 150000,
      modelTier: 'hard',
      modelSource: 'reasoning-core',
      toolCalls: 0,
      actualCredits: 11,
      tokenUsage: {
        inputTokens: 5400,
        outputTokens: 1200,
        totalTokens: 6600,
      },
      summary: 'Produced a recommendation with a clear trade-off section and confidence call.',
    },
    {
      stepId: 'guardrail-review',
      kind: 'note',
      title: 'Review policy and citation coverage',
      assignedRole: 'reviewer',
      status: 'succeeded',
      startedAt: '2026-04-17T13:07:38.000Z',
      finishedAt: '2026-04-17T13:08:40.000Z',
      durationMs: 62000,
      modelTier: 'default',
      modelSource: 'review-core',
      toolCalls: 1,
      actualCredits: 2,
      tokenUsage: {
        inputTokens: 1200,
        outputTokens: 320,
        totalTokens: 1520,
      },
      summary: 'Confirmed citation coverage and allowed the brief to publish.',
    },
    {
      stepId: 'publish-brief',
      kind: 'deliver',
      title: 'Publish the final brief',
      assignedRole: 'publisher',
      status: 'succeeded',
      startedAt: '2026-04-17T13:08:42.000Z',
      finishedAt: '2026-04-17T13:09:20.000Z',
      durationMs: 38000,
      modelTier: 'default',
      modelSource: 'delivery',
      toolCalls: 1,
      actualCredits: 1,
      summary: 'Delivered the final brief and stored the replay artifact.',
    },
  ],
  policy: seededWorkflow.policy,
  studioState: seededStudioState,
  operationalContext: seededOperationalContexts[seededIds.baselineRunId],
};

const degradedReplay: Replay = {
  workflow: seededWorkflow,
  run: seededRuns[1],
  stepExecutions: [
    {
      stepId: 'capture-intake',
      kind: 'capture',
      title: 'Capture intake and context',
      assignedRole: 'coordinator',
      status: 'succeeded',
      startedAt: '2026-04-18T13:00:00.000Z',
      finishedAt: '2026-04-18T13:01:22.000Z',
      durationMs: 82000,
      modelTier: 'micro',
      modelSource: 'control-room',
      directiveMode: 'cheaper',
      directivePhases: ['capture', 'search'],
      toolCalls: 1,
      actualCredits: 4,
      tokenUsage: {
        inputTokens: 2200,
        outputTokens: 670,
        totalTokens: 2870,
      },
      summary: 'Normalized the request but kept a wider-than-needed intake queue.',
    },
    {
      stepId: 'collect-evidence',
      kind: 'search',
      title: 'Collect supporting evidence',
      assignedRole: 'researcher',
      status: 'succeeded',
      startedAt: '2026-04-18T13:01:24.000Z',
      finishedAt: '2026-04-18T13:03:49.000Z',
      durationMs: 145000,
      modelTier: 'micro',
      modelSource: 'search-runtime',
      directiveMode: 'cheaper',
      directivePhases: ['search'],
      toolCalls: 6,
      actualCredits: 10,
      tokenUsage: {
        inputTokens: 4700,
        outputTokens: 980,
        totalTokens: 5680,
      },
      summary: 'Pulled in extra sources, which increased duplication without improving confidence.',
    },
    {
      stepId: 'normalize-evidence',
      kind: 'capture',
      title: 'Normalize notes into a fact table',
      assignedRole: 'annotator',
      status: 'succeeded',
      startedAt: '2026-04-18T13:03:52.000Z',
      finishedAt: '2026-04-18T13:05:40.000Z',
      durationMs: 108000,
      modelTier: 'default',
      modelSource: 'notes-engine',
      toolCalls: 2,
      actualCredits: 6,
      tokenUsage: {
        inputTokens: 3100,
        outputTokens: 860,
        totalTokens: 3960,
      },
      summary: 'Repeated citations needed a cleanup pass before synthesis could continue.',
    },
    {
      stepId: 'synthesize-brief',
      kind: 'analyze',
      title: 'Synthesize the recommendation',
      assignedRole: 'analyst',
      status: 'succeeded',
      startedAt: '2026-04-18T13:05:44.000Z',
      finishedAt: '2026-04-18T13:08:34.000Z',
      durationMs: 170000,
      modelTier: 'hard',
      modelSource: 'reasoning-core',
      toolCalls: 0,
      actualCredits: 12,
      tokenUsage: {
        inputTokens: 6000,
        outputTokens: 1400,
        totalTokens: 7400,
      },
      summary: 'Recovered from the noisy evidence table but had to restate several facts.',
    },
    {
      stepId: 'guardrail-review',
      kind: 'note',
      title: 'Review policy and citation coverage',
      assignedRole: 'reviewer',
      status: 'failed',
      startedAt: '2026-04-18T13:08:38.000Z',
      finishedAt: '2026-04-18T13:09:40.000Z',
      durationMs: 62000,
      modelTier: 'default',
      modelSource: 'review-core',
      toolCalls: 1,
      actualCredits: 2,
      tokenUsage: {
        inputTokens: 1300,
        outputTokens: 350,
        totalTokens: 1650,
      },
      summary: 'Detected incomplete citation coverage before publish.',
      error: 'Policy coverage was incomplete: two claims had no source trace.',
    },
    {
      stepId: 'publish-brief',
      kind: 'deliver',
      title: 'Publish the final brief',
      assignedRole: 'publisher',
      status: 'skipped',
      startedAt: '2026-04-18T13:09:40.000Z',
      finishedAt: '2026-04-18T13:10:40.000Z',
      durationMs: 60000,
      modelTier: 'default',
      modelSource: 'delivery',
      toolCalls: 0,
      actualCredits: 1,
      summary: 'Skipped because review failed.',
    },
  ],
  policy: {
    mode: 'custom',
    optimizationGoal: 'cost_saver',
    reviewPolicy: 'lean',
    maxElasticLanes: 1,
  },
  studioState: seededStudioState,
  operationalContext: seededOperationalContexts[seededIds.degradedRunId],
};

const improvedReplay: Replay = {
  workflow: seededWorkflow,
  run: seededRuns[2],
  stepExecutions: [
    {
      stepId: 'capture-intake',
      kind: 'capture',
      title: 'Capture intake and context',
      assignedRole: 'coordinator',
      status: 'succeeded',
      startedAt: '2026-04-19T13:00:00.000Z',
      finishedAt: '2026-04-19T13:01:10.000Z',
      durationMs: 70000,
      modelTier: 'micro',
      modelSource: 'control-room',
      directiveMode: 'cheaper',
      directivePhases: ['capture', 'search'],
      toolCalls: 1,
      actualCredits: 3,
      tokenUsage: {
        inputTokens: 1900,
        outputTokens: 600,
        totalTokens: 2500,
      },
      summary: 'Normalized the request and trimmed it to a narrower evidence frame.',
    },
    {
      stepId: 'collect-evidence',
      kind: 'search',
      title: 'Collect supporting evidence',
      assignedRole: 'researcher',
      status: 'succeeded',
      startedAt: '2026-04-19T13:01:12.000Z',
      finishedAt: '2026-04-19T13:02:53.000Z',
      durationMs: 101000,
      modelTier: 'micro',
      modelSource: 'search-runtime',
      directiveMode: 'cheaper',
      directivePhases: ['search'],
      toolCalls: 3,
      actualCredits: 6,
      tokenUsage: {
        inputTokens: 3000,
        outputTokens: 820,
        totalTokens: 3820,
      },
      summary: 'Collected the right sources without the duplicate fan-out seen in the degraded replay.',
    },
    {
      stepId: 'normalize-evidence',
      kind: 'capture',
      title: 'Normalize notes into a fact table',
      assignedRole: 'annotator',
      status: 'succeeded',
      startedAt: '2026-04-19T13:02:55.000Z',
      finishedAt: '2026-04-19T13:04:08.000Z',
      durationMs: 73000,
      modelTier: 'default',
      modelSource: 'notes-engine',
      toolCalls: 1,
      actualCredits: 4,
      tokenUsage: {
        inputTokens: 2200,
        outputTokens: 680,
        totalTokens: 2880,
      },
      summary: 'Produced a smaller fact table that still preserved all citations.',
    },
    {
      stepId: 'synthesize-brief',
      kind: 'analyze',
      title: 'Synthesize the recommendation',
      assignedRole: 'analyst',
      status: 'succeeded',
      startedAt: '2026-04-19T13:04:10.000Z',
      finishedAt: '2026-04-19T13:06:08.000Z',
      durationMs: 118000,
      modelTier: 'hard',
      modelSource: 'reasoning-core',
      toolCalls: 0,
      actualCredits: 5,
      tokenUsage: {
        inputTokens: 4200,
        outputTokens: 980,
        totalTokens: 5180,
      },
      summary: 'Generated the same recommendation shape as the baseline with fewer duplicate notes.',
    },
    {
      stepId: 'guardrail-review',
      kind: 'note',
      title: 'Review policy and citation coverage',
      assignedRole: 'reviewer',
      status: 'succeeded',
      startedAt: '2026-04-19T13:06:10.000Z',
      finishedAt: '2026-04-19T13:07:14.000Z',
      durationMs: 64000,
      modelTier: 'default',
      modelSource: 'review-core',
      toolCalls: 1,
      actualCredits: 1,
      tokenUsage: {
        inputTokens: 1100,
        outputTokens: 280,
        totalTokens: 1380,
      },
      summary: 'Confirmed that the citation trace stayed complete and publish-ready.',
    },
    {
      stepId: 'publish-brief',
      kind: 'deliver',
      title: 'Publish the final brief',
      assignedRole: 'publisher',
      status: 'succeeded',
      startedAt: '2026-04-19T13:07:16.000Z',
      finishedAt: '2026-04-19T13:07:54.000Z',
      durationMs: 38000,
      modelTier: 'default',
      modelSource: 'delivery',
      toolCalls: 1,
      actualCredits: 1,
      summary: 'Published the brief and stored the replay artifact for future comparisons.',
    },
  ],
  policy: {
    mode: 'custom',
    optimizationGoal: 'balanced',
    reviewPolicy: 'standard',
    maxElasticLanes: 1,
  },
  studioState: seededStudioState,
  operationalContext: seededOperationalContexts[seededIds.improvedRunId],
};

export const seededReplays = [baselineReplay, degradedReplay, improvedReplay] satisfies Replay[];

export const seededReplayByRunId = {
  [seededIds.baselineRunId]: baselineReplay,
  [seededIds.degradedRunId]: degradedReplay,
  [seededIds.improvedRunId]: improvedReplay,
} satisfies Record<string, Replay>;
